services:
  app:
    build: .
    container_name: spring-app
    restart: unless-stopped

    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=local

  nginx:

    image: nginx:latest
    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - app
    restart: unless-stopped #ec2 재부팅이나 컨테이너가 죽었을 때 자동 재시작