services:
  app:
    build: .
    container_name: spring-app

  nginx:
    image: nginx:latest
    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - app